const MINIMUM_VALUE = 0
    , MAXIMUM_VALUE = 256
    , CHARACTER_LENGTH = 8
    , GENERATION_LENGTH = 8
    , ITERATIONS = 50
    , SWAP_CHANCE = 0.7
    , EXTREMUM_MODE = 0

export {
    MINIMUM_VALUE,
    MAXIMUM_VALUE,
    CHARACTER_LENGTH,
    GENERATION_LENGTH,
    ITERATIONS,
    SWAP_CHANCE,
    EXTREMUM_MODE,
}